#!/bin/bash
set -e

# Build script for Gorgeous Installer

CLEAN=false
USE_UPX=false
SKIP_UPX=false
CROSS_WINDOWS=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --clean) CLEAN=true ;;
        --use-upx) USE_UPX=true ;;
        --skip-upx) SKIP_UPX=true ;;
        --cross-windows) CROSS_WINDOWS=true ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

if ! command -v gcc &> /dev/null; then
    echo "gcc compiler not found. Please install gcc."
    exit 1
fi

export CGO_ENABLED=${CGO_ENABLED:-"1"}
export CC=${CC:-"gcc"}
export CXX=${CXX:-"g++"}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

GOOS=${GOOS:-$(go env GOOS)}
GOARCH=${GOARCH:-$(go env GOARCH)}
export GOOS GOARCH

BUILD_DIR="$SCRIPT_DIR/build"
if [ "$GOOS" = "windows" ]; then
    EXE_PATH="$BUILD_DIR/gorgeous-installer.exe"
else
    EXE_PATH="$BUILD_DIR/gorgeous-installer"
fi

if [ "$USE_UPX" = true ] && [ "$SKIP_UPX" = true ]; then
    echo "--use-upx and --skip-upx cannot be used together"
    exit 1
fi

echo "Building Gorgeous Installer for Linux..."

if [ "$CLEAN" = true ]; then
    echo "Cleaning previous artifacts..."
    rm -rf "$BUILD_DIR"
    rm -f gorgeous-installer gorgeous-installer-debug resource.syso
fi

mkdir -p "$BUILD_DIR"

if [ ! -f "config.json" ]; then
    echo "config.json not found in project root"
    exit 1
fi

# Ensure SHA manifests
generate_sha_manifest() {
    local pack_root="$1"
    local manifest_path="$2"
    
    if [ ! -d "$pack_root" ]; then
        echo "Pack path not found: $pack_root"
        exit 1
    fi
    
    mkdir -p "$(dirname "$manifest_path")"
    
    find "$pack_root" -type f | while read -r file; do
        if [[ "$file" == *.sha ]] || [[ "$file" == *.sha256 ]] || [[ "$file" == *.sha512 ]] || [[ "$file" == *manifest.sha256 ]]; then
            continue
        fi
        hash=$(sha256sum "$file" | awk '{print $1}')
        rel_path="${file#$pack_root/}"
        echo "$hash  $rel_path"
    done > "$manifest_path"
}

# Find all versions in config.json and generate manifests
PACKS=$(grep -o '"path": *"[^"]*"' config.json | cut -d'"' -f4 || true)
SHAS=$(grep -o '"shaFile": *"[^"]*"' config.json | cut -d'"' -f4 || true)

paste <(echo "$PACKS") <(echo "$SHAS") | while read -r pack sha_file; do
    if [ -n "$pack" ] && [ -n "$sha_file" ]; then
        if [ -d "$pack" ]; then
            echo "Generating SHA manifest for $pack -> $sha_file"
            generate_sha_manifest "$pack" "$sha_file"
        fi
    fi
done

# Build info
VERSION="1.0.0"
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
PLATFORM=$(uname -s)_$(uname -m)

cat << INFO_EOF > internal/buildinfo/buildinfo.go
// Code generated by build.sh. DO NOT EDIT.
package buildinfo

const (
    Version   = "$VERSION"
    GitCommit = "$GIT_HASH"
    BuildTime = "$BUILD_TIME"
    Platform  = "$PLATFORM"
)

func Summary() string {
    return "Gorgeous Installer " + Version + " (" + Platform + ") - " + GitCommit + " @ " + BuildTime
}
INFO_EOF

resolve_upx() {
    if command -v upx &> /dev/null; then
        echo "upx"
        return
    fi
    
    TOOLS_DIR="$SCRIPT_DIR/.tools"
    LOCAL_UPX="$TOOLS_DIR/upx"
    
    if [ -x "$LOCAL_UPX" ]; then
        echo "$LOCAL_UPX"
        return
    fi
    
    echo "UPX not found in PATH. Automatically downloading UPX..." >&2
    mkdir -p "$TOOLS_DIR"
    
    OS_NAME=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)
    
    if [ "$OS_NAME" = "darwin" ]; then
        echo "Official prebuilt UPX binaries are not available for macOS." >&2
        echo "Please install UPX via Homebrew: brew install upx" >&2
        return
    elif [ "$OS_NAME" = "linux" ]; then
        if [ "$ARCH" = "x86_64" ]; then
            UPX_URL="https://github.com/upx/upx/releases/download/v5.2.0/upx-5.2.0-amd64_linux.tar.xz"
            DIR_NAME="upx-5.2.0-amd64_linux"
        elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
            UPX_URL="https://github.com/upx/upx/releases/download/v5.2.0/upx-5.2.0-arm64_linux.tar.xz"
            DIR_NAME="upx-5.2.0-arm64_linux"
        else
            echo "Unsupported architecture for UPX auto-download: $ARCH" >&2
            return
        fi
    else
        echo "Unsupported OS for UPX auto-download: $OS_NAME" >&2
        return
    fi
    
    TAR_PATH="$TOOLS_DIR/upx.tar.xz"
    curl -sL "$UPX_URL" -o "$TAR_PATH" || return
    tar -xf "$TAR_PATH" -C "$TOOLS_DIR" || return
    
    if [ -f "$TOOLS_DIR/$DIR_NAME/upx" ]; then
        cp "$TOOLS_DIR/$DIR_NAME/upx" "$LOCAL_UPX"
        chmod +x "$LOCAL_UPX"
    fi
    
    rm -f "$TAR_PATH"
    rm -rf "$TOOLS_DIR/$DIR_NAME"
    
    if [ -x "$LOCAL_UPX" ]; then
        echo "$LOCAL_UPX"
    fi
}

echo "Compiling native Go application..."
go build -ldflags "-s -w" -o "$EXE_PATH" ./cmd/main

if [ "$SKIP_UPX" = false ]; then
    UPX_BIN=$(resolve_upx)
    if [ -n "$UPX_BIN" ]; then
        echo "Compressing executable with UPX..."
        "$UPX_BIN" --best --lzma "$EXE_PATH" || echo "UPX compression failed"
    elif [ "$USE_UPX" = true ]; then
        echo "UPX requested but could not be resolved or downloaded"
        exit 1
    else
        echo "UPX not found and auto-download failed; build continues uncompressed."
    fi
fi

echo "Generating build metadata..."
sha256sum "$EXE_PATH" > "$EXE_PATH.sha256"

cat << META_EOF > "$BUILD_DIR/gorgeous-installer.build.json"
{
  "version": "$VERSION",
  "commit": "$GIT_HASH",
  "buildTime": "$BUILD_TIME",
  "platform": "$PLATFORM",
  "sizeBytes": $(stat -c%s "$EXE_PATH")
}
META_EOF

cat <<EOF > "build/gorgeous-installer.desktop"
[Desktop Entry]
Version=$VERSION
Type=Application
Name=Gorgeous Installer
Comment=Installation and recompilation tool for Gorgeous plugins
Exec=$(pwd)/build/gorgeous-installer
Icon=$(pwd)/icon.png
Terminal=false
Categories=Development;
EOF

# ── Windows cross-compile ──────────────────────────────────────────────────
if [ "$CROSS_WINDOWS" = true ]; then
    WIN_EXE="$BUILD_DIR/gorgeous-installer.exe"
    WIN_CC="x86_64-w64-mingw32-gcc"

    if ! command -v "$WIN_CC" &> /dev/null; then
        echo "Warning: $WIN_CC not found – skipping Windows cross-compile."
        echo "Install mingw-w64 (e.g. sudo apt install gcc-mingw-w64-x86-64) to enable it."
    else
        echo "Cross-compiling for Windows (amd64)..."
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC="$WIN_CC" \
            go build -ldflags "-s -w -H windowsgui" -o "$WIN_EXE" ./cmd/main

        if [ "$SKIP_UPX" = false ]; then
            WIN_UPX_BIN=$(resolve_upx)
            if [ -n "$WIN_UPX_BIN" ]; then
                echo "Compressing Windows executable with UPX..."
                "$WIN_UPX_BIN" --best --lzma "$WIN_EXE" || echo "UPX compression failed for Windows build"
            fi
        fi

        sha256sum "$WIN_EXE" > "$WIN_EXE.sha256"
        echo "Windows build: $WIN_EXE"
    fi
fi

echo "Build successful! Output in $(pwd)/build"
