// Code generated by build.sh. DO NOT EDIT.
package buildinfo

const (
    Version   = "1.0.0"
    GitCommit = "0647ebe"
    BuildTime = "2026-06-22T18:51:29Z"
    Platform  = "Linux_x86_64"
)

func Summary() string {
    return "Gorgeous Installer " + Version + " (" + Platform + ") - " + GitCommit + " @ " + BuildTime
}
