// Code generated by build.sh. DO NOT EDIT.
package buildinfo

const (
    Version   = "1.0.0"
    GitCommit = "28b3476"
    BuildTime = "2026-06-20T20:53:45Z"
    Platform  = "Linux_x86_64"
)

func Summary() string {
    return "Gorgeous Installer " + Version + " (" + Platform + ") - " + GitCommit + " @ " + BuildTime
}
